# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Niyanta Pandey
title: Associate QA engineer
email: niyantapandey@gmail.com
website: https://niyanta5.github.io/niyanta.github.io/

# Social links
twitter_username: https://twitter.com/niyanta
github_username:  https://github.com/niyanta5
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: https://linkedin.com/niyantapandey
# pinterest_username: jekyll
youtube_username: niyantapandey
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
QA engineer experienced  in software development processes and optimal testing strategies. Helps teams produce better products by offering in-depth quality assurance support. Open and clear communicator with good multitasking skills, organized nature and strong attention to detail.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and QA engineering, some of my other interests and hobbies are:
   - Singing
   - Traveling
   - Sketches

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
